# hidden states - bus stops
entities:
    - Washington Blvd
    - Washington Place
    - Barbara
    - Venice
    - Charnock 
    - Palms
    - Woodbine
    - Rose
    - Airport
    - National 
    - Ocean Park Blvd
    - Pearl
    - Pico
    - Olympic

# observable conditions - boarder count sets
conditions: 
    - 0-2
    - 3-6
    - 7+

# training set - observed boarder counts at bus stops
training_set:
    ride01: 
        - ['0-2', 'Washington Blvd']
        - ['7+', 'Venice']
        - ['0-2', 'Palms']
        - ['0-2', 'Ocean Park Blvd']
        - ['3-6', 'Pico']
    ride02:
        - ['3-6', 'Washington Place']
        - ['3-6', 'Venice']
        - ['0-2', 'Rose']
        - ['7+', 'Pico']
        - ['0-2', 'Olympic']
    ride03:
        - ['0-2', 'Washington Place']
        - ['0-2', 'Barbara']
        - ['0-2', 'Venice']
        - ['0-2', 'Woodbine']
        - ['3-6', 'Pico']
        - ['0-2', 'Olympic']
    ride04:
        - ['7+', 'Washington Blvd']
        - ['3-6', 'Venice']
        - ['7+', 'Pico']
        - ['3-6', 'Olympic']
    ride05:
        - ['0-2', 'Washington Place']
        - ['3-6', 'Venice']
        - ['0-2', 'Woodbine']
        - ['0-2', 'Rose']
        - ['7+', 'Pico']
        - ['0-2', 'Olympic']
    wrong_route:
        - ['0-2', 'Union Station']
    bad_set:
        - ['12+', 'Rose']

